/** Declaration file generated by dts-gen */

export function generate(options: any): any;

export function generateMultiple(amount: any, options: any): any;

export namespace generate {
    const prototype: {
    };

}

export namespace generateMultiple {
    const prototype: {
    };

}

