/** Declaration file generated by dts-gen */

declare module "node-google-calendar" {
    export default class node_google_calendar {
        constructor(...args: any[]);

        static prototype: {
            Acl: any;
            CalendarList: any;
            Calendars: any;
            Channels: any;
            Colors: any;
            Events: any;
            FreeBusy: any;
            Settings: any;
        };

    }
}

