/** Declaration file generated by dts-gen */
declare module "swagger-routes-express" {
    export function connector(api: any, apiDoc: any, options: any): any;

    export function summarise(apiDoc: any, options: any): any;
}



